<h1>Materiais cadastrados</h1>
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Material</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->materiais as $material): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($material->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($material->getDescricao()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('metabsoy/material', ['action' => 'save', 'id' => $material->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('metabsoy/material', ['action' => 'delete', 'id' => $material->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->materiais, 'Elastic', 'metabsoy/partial/paginator', ['route' => 'metabsoy/material']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/metabsoy/material/save">Novo registro</a>
</div>
