<br>
<div class="jumbotron">

    <h1>MetabSoy</h1>
    <p>
        Banco de Dados de Metabólitos Secundários da Soja
    </p>
    <hr>
    <p>
        Dados de metabólitos presentes em genótipos de soja
        relacionados à interação inseto-planta, a
        resistência e tolerância a percevejos e outros insetos.
    </p>
    <hr>
    <p>
        Usuário: <?php echo $this->user->getNome()." ".$user->getPapel() ?>
    </p>
</div>

