<div class="jumbotron">
    <h3>Bem Vindo, <?php echo $this->user->getNome()?>!</h3>
    <hr>
    <p>
        A base de dados "Banco de Dados de Metabólitos Secundários 
        de Soja e outras Espécies Vegetais que Compõem o seu 
        Sistema", contem dados de compostos secundários de plantas 
        obtido por análises cromatográficas e espectrométricas.
    </p>

    <p>
        Esse documento contém características que permitem a 
        identificação e quantificação dos metabólitos de interesse,
        pela comparação de dados de tempo de retenção (tR), 
        espectro (UVVis ) e intensidade de absorbância, que permite
        a quantificação dos compostos. Fornece também a massa (m/z)
        dos metabólitos secundários constitutivos e/ou induzidos
        por estresses bióticos e abióticos extraídos de soja e 
        outras plantas que compõem o sistema.
    </p>
    
   
</div>
