<h1>Ambientes cadastrados</h1>
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Ambiente</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->ambientes as $ambiente): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($ambiente->getDescricao()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('metabsoy/ambiente', ['action' => 'save', 'id' => $ambiente->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('metabsoy/ambiente', ['action' => 'delete', 'id' => $ambiente->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->ambientes, 'Elastic', 'metabsoy/partial/paginator', ['route' => 'metabsoy/ambiente']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/metabsoy/ambiente/save">Novo registro</a>
</div>
